name: forest-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - antlr-python-runtime=4.7.2
  - asn1crypto=0.24.0
  - bokeh=1.3.4
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - cartopy=0.17.0
  - certifi=2019.9.11
  - cf-units=2.1.3
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.2
  - cryptography=2.7
  - curl=7.65.3
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask=2.5.0
  - dask-core=2.5.0
  - distributed=2.5.0
  - expat=2.2.5
  - freetype=2.10.0
  - fsspec=0.5.1
  - geos=3.7.2
  - hdf4=4.2.13
  - hdf5=1.10.5
  - heapdict=1.0.1
  - idna=2.8
  - iris=2.2.1
  - jinja2=2.10.1
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - libtiff=4.0.10
  - llvm-openmp=9.0.0
  - locket=0.2.0
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=2.2.3
  - msgpack-python=0.6.2
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - numpy=1.17.2
  - olefile=0.46
  - openssl=1.1.1c
  - owslib=0.18.0
  - packaging=19.2
  - pandas=0.25.1
  - partd=1.0.0
  - pillow=6.1.0
  - pip=19.2.3
  - proj4=5.2.0
  - psutil=5.6.3
  - pycparser=2.19
  - pyepsg=0.4.0
  - pykdtree=1.3.1
  - pyke=1.1.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyproj=1.9.6
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyyaml=5.1.2
  - readline=7.0
  - requests=2.22.0
  - scipy=1.3.1
  - setuptools=41.2.0
  - shapely=1.6.4
  - six=1.12.0
  - sortedcontainers=2.1.0
  - sqlite=3.29.0
  - tblib=1.4.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - udunits2=2.2.27.6
  - urllib3=1.25.6
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zict=1.0.0
  - zlib=1.2.11
  - zstd=1.4.0

