files:
        - label: Operational GA6
          pattern: '*global_africa*.nc'
          locator: database
          file_type: unified_model
          directory: unified_model
        - label: Operational Tropical Africa
          pattern: '*os42_ea*.nc'
          locator: database
          file_type: unified_model
          directory: unified_model
        - label: EIDA50
          pattern: 'eida50/EIDA50_takm4p4*.nc'
          locator: file_system
          file_type: eida50
        - label: RDT
          pattern: 'rdt_json/*.json'
          locator: file_system
          file_type: rdt
