files:
        - label: Operational GA6 Africa
          pattern: '*global_africa*.nc'
          locator: database
          file_type: unified_model
          directory: unified_model
        - label: Operational GA6 SE Asia
          pattern: '*oper_global_south_east_asia*.nc'
          locator: database
          file_type: unified_model
          directory: unified_model
        - label: Operational Tropical Africa
          pattern: '*os42_ea*.nc'
          locator: database
          file_type: unified_model
          directory: unified_model
        - label: Tanzania WRF
          pattern: '*wrf_sampledata.nc'
          locator: database
          file_type: unified_model
          directory: tma_wrf
        - label: EIDA50
          pattern: 'eida50/EIDA50_takm4p4*.nc'
          locator: file_system
          file_type: eida50
        - label: RDT
          pattern: 'rdt_json/*.json'
          locator: file_system
          file_type: rdt
