models:
        - name: Operational GA6
          pattern: '*global_africa*.nc'
        - name: Operational Tropical Africa
          pattern: '*os42_ea*.nc'
        - name: EIDA50
          directory: ~/cache
          pattern: EIDA50*.nc
